version: 'latest'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://hirunadesilva:hiruna_72@cluster0.ni03buq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo-data:
