// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Delete User', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Delete User', async function() {
    await driver.get("http://localhost:3000/users")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(7) > .MuiTableCell-root:nth-child(9) > .MuiButtonBase-root")).click()
    assert(await driver.switchTo().alert().getText() == "Do you want to delete this user?")
    await driver.switchTo().alert().accept()
  })
})
